"""
Type definitions for Polymarket APIs.

This module contains all the Pydantic models and type definitions used across
the Polymarket APIs.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..utilities.order_builder.model import SignedOrder
    from .clob_types import (
        ApiCreds,
        AssetType,
        BalanceAllowanceParams,
        BidAsk,
        BookParams,
        ClobFeeData,
        ClobMarket,
        ClobMarketInfo,
        ClobMarketInfoRewards,
        ClobMarketInfoToken,
        ContractConfig,
        CreateOrderOptions,
        CryptoOutcome,
        DailyEarnedReward,
        DropNotificationParams,
        EarnedReward,
        FeeInfo,
        MarketIDs,
        MarketOrderArgs,
        MarketRewards,
        MakerOrder,
        Midpoint,
        OpenOrder,
        OpenOrderParams,
        OrderArgs,
        OrderBookSummary,
        OrderCancelResponse,
        OrderPostResponse,
        OrderSummary,
        OrderType,
        PaginatedResponse,
        PastResultsData,
        PastResultsResponse,
        PartialCreateOrderOptions,
        PolygonTrade,
        PostOrdersArgs,
        Price,
        PriceHistory,
        PriceLevel,
        RequestArgs,
        RewardConfig,
        RewardMarket,
        RewardRate,
        Rewards,
        RoundConfig,
        SignatureType,
        Spread,
        TickSize,
        Token,
        TokenBidAsk,
        TokenBidAskDict,
        TokenValue,
        TokenValueDict,
        TradeParams,
    )
    from .common import (
        EmptyString,
        EthAddress,
        FlexibleDatetime,
        HexString,
        Keccak256,
        Keccak256OrPadded,
        TimeseriesPoint,
    )
    from .data_types import (
        AccountingSnapshotCSVs,
        Activity,
        ActivityType,
        BuilderLeaderboardUser,
        ClosedPosition,
        EventLiveVolume,
        GQLPosition,
        Holder,
        HolderResponse,
        LeaderboardUser,
        MarketValue,
        Position,
        Trade,
        User,
        UserID,
        UserMetric,
        UserProfile,
        UserRank,
        ValueResponse,
    )
    from .gamma_types import (
        Category,
        Chat,
        ClobReward,
        Collection,
        Comment,
        Creator,
        Event,
        FeeSchedule,
        GammaMarket,
        OptimizedImage,
        Pagination,
        Profile,
        ProfilePosition,
        Reaction,
        SearchResult,
        Series,
        Sport,
        Tag,
        TagRelation,
        Team,
        Template,
    )
    from .web3_types import DepositWalletCall, TransactionLog, TransactionReceipt
    from .websockets_types import (
        AggOrderBookSummary,
        ActivityOrderMatchEvent,
        ActivityTradeEvent,
        ActivityTrade,
        AssetPriceSubscribe,
        AssetPriceSubscribeEvent,
        AssetPriceUpdate,
        AssetPriceUpdateEvent,
        BestBidAskEvent,
        CommentEvent,
        CryptoPriceSubscribe,
        CryptoPriceSubscribeEvent,
        CryptoPriceUpdate,
        CryptoPriceUpdateEvent,
        ErrorEvent,
        LastTradePrice,
        LastTradePriceEvent,
        LiveDataClobMarket,
        LiveDataEvents,
        LiveDataLastTradePriceEvent,
        LiveDataOrderBookSummaryEvent,
        LiveDataOrderEvent,
        LiveDataPriceChangeEvent,
        LiveDataTickSizeChangeEvent,
        LiveDataTradeEvent,
        MarketEvent,
        MarketEvents,
        MarketResolvedEvent,
        MarketStatusChangeEvent,
        NewMarketEvent,
        OrderBookSummaryEvent,
        OrderEvent,
        PriceChange,
        PriceChangeEvent,
        PriceChanges,
        Quote,
        QuoteEvent,
        ReactionEvent,
        RelatedEvent,
        Request,
        RequestEvent,
        ScoreStateFields,
        SportsGameUpdate,
        SportsEventState,
        TickSizeChange,
        TickSizeChangeEvent,
        TradeEvent,
        UserEvents,
    )

__all__ = [
    "AccountingSnapshotCSVs",
    "Activity",
    "ActivityTrade",
    "AggOrderBookSummary",
    "ActivityOrderMatchEvent",
    "ActivityTradeEvent",
    "ActivityType",
    "ApiCreds",
    "AssetPriceSubscribe",
    "AssetPriceSubscribeEvent",
    "AssetPriceUpdate",
    "AssetPriceUpdateEvent",
    "AssetType",
    "BalanceAllowanceParams",
    "BestBidAskEvent",
    "BidAsk",
    "BookParams",
    "BuilderLeaderboardUser",
    "Category",
    "Chat",
    "ClobFeeData",
    "ClobMarket",
    "ClobMarketInfo",
    "ClobMarketInfoRewards",
    "ClobMarketInfoToken",
    "ClobReward",
    "ClosedPosition",
    "Collection",
    "Comment",
    "CommentEvent",
    "ContractConfig",
    "Creator",
    "CryptoOutcome",
    "CryptoPriceSubscribe",
    "CryptoPriceSubscribeEvent",
    "CryptoPriceUpdate",
    "CryptoPriceUpdateEvent",
    "CreateOrderOptions",
    "DailyEarnedReward",
    "DepositWalletCall",
    "DropNotificationParams",
    "EarnedReward",
    "EmptyString",
    "ErrorEvent",
    "EthAddress",
    "Event",
    "EventLiveVolume",
    "FeeSchedule",
    "FeeInfo",
    "FlexibleDatetime",
    "GammaMarket",
    "GQLPosition",
    "HexString",
    "Holder",
    "HolderResponse",
    "Keccak256",
    "Keccak256OrPadded",
    "LastTradePrice",
    "LastTradePriceEvent",
    "LeaderboardUser",
    "LiveDataClobMarket",
    "LiveDataEvents",
    "LiveDataLastTradePriceEvent",
    "LiveDataOrderBookSummaryEvent",
    "LiveDataOrderEvent",
    "LiveDataPriceChangeEvent",
    "LiveDataTickSizeChangeEvent",
    "LiveDataTradeEvent",
    "MakerOrder",
    "MarketEvent",
    "MarketEvents",
    "MarketIDs",
    "MarketOrderArgs",
    "MarketResolvedEvent",
    "MarketRewards",
    "MarketStatusChangeEvent",
    "MarketValue",
    "Midpoint",
    "NewMarketEvent",
    "OpenOrder",
    "OpenOrderParams",
    "OrderArgs",
    "OrderBookSummary",
    "OrderBookSummaryEvent",
    "OrderCancelResponse",
    "OrderEvent",
    "OrderPostResponse",
    "OrderSummary",
    "OrderType",
    "OptimizedImage",
    "PaginatedResponse",
    "Pagination",
    "PastResultsData",
    "PastResultsResponse",
    "PartialCreateOrderOptions",
    "PolygonTrade",
    "Position",
    "PostOrdersArgs",
    "Price",
    "PriceChange",
    "PriceChangeEvent",
    "PriceChanges",
    "PriceHistory",
    "PriceLevel",
    "Profile",
    "ProfilePosition",
    "Quote",
    "QuoteEvent",
    "Reaction",
    "ReactionEvent",
    "RelatedEvent",
    "Request",
    "RequestArgs",
    "RequestEvent",
    "RewardConfig",
    "RewardMarket",
    "RewardRate",
    "Rewards",
    "RoundConfig",
    "ScoreStateFields",
    "SearchResult",
    "Series",
    "SignatureType",
    "SignedOrder",
    "Sport",
    "SportsGameUpdate",
    "SportsEventState",
    "Spread",
    "Tag",
    "TagRelation",
    "Team",
    "Template",
    "TickSize",
    "TickSizeChange",
    "TickSizeChangeEvent",
    "TimeseriesPoint",
    "Token",
    "TokenBidAsk",
    "TokenBidAskDict",
    "TokenValue",
    "TokenValueDict",
    "Trade",
    "TradeParams",
    "TradeEvent",
    "TransactionLog",
    "TransactionReceipt",
    "User",
    "UserEvents",
    "UserID",
    "UserMetric",
    "UserProfile",
    "UserRank",
    "ValueResponse",
]

_EXPORT_MAP = {
    "AccountingSnapshotCSVs": ".data_types",
    "Activity": ".data_types",
    "ActivityTrade": ".websockets_types",
    "AggOrderBookSummary": ".websockets_types",
    "ActivityOrderMatchEvent": ".websockets_types",
    "ActivityTradeEvent": ".websockets_types",
    "ActivityType": ".data_types",
    "ApiCreds": ".clob_types",
    "AssetPriceSubscribe": ".websockets_types",
    "AssetPriceSubscribeEvent": ".websockets_types",
    "AssetPriceUpdate": ".websockets_types",
    "AssetPriceUpdateEvent": ".websockets_types",
    "AssetType": ".clob_types",
    "BalanceAllowanceParams": ".clob_types",
    "BestBidAskEvent": ".websockets_types",
    "BidAsk": ".clob_types",
    "BookParams": ".clob_types",
    "BuilderLeaderboardUser": ".data_types",
    "Category": ".gamma_types",
    "Chat": ".gamma_types",
    "ClobFeeData": ".clob_types",
    "ClobMarket": ".clob_types",
    "ClobMarketInfo": ".clob_types",
    "ClobMarketInfoRewards": ".clob_types",
    "ClobMarketInfoToken": ".clob_types",
    "MarketIDs": ".clob_types",
    "ClobReward": ".gamma_types",
    "ClosedPosition": ".data_types",
    "Collection": ".gamma_types",
    "Comment": ".gamma_types",
    "CommentEvent": ".websockets_types",
    "ContractConfig": ".clob_types",
    "Creator": ".gamma_types",
    "CryptoOutcome": ".clob_types",
    "CryptoPriceSubscribe": ".websockets_types",
    "CryptoPriceSubscribeEvent": ".websockets_types",
    "CryptoPriceUpdate": ".websockets_types",
    "CryptoPriceUpdateEvent": ".websockets_types",
    "CreateOrderOptions": ".clob_types",
    "DailyEarnedReward": ".clob_types",
    "DepositWalletCall": ".web3_types",
    "DropNotificationParams": ".clob_types",
    "EarnedReward": ".clob_types",
    "EmptyString": ".common",
    "ErrorEvent": ".websockets_types",
    "EthAddress": ".common",
    "Event": ".gamma_types",
    "EventLiveVolume": ".data_types",
    "FeeSchedule": ".gamma_types",
    "FeeInfo": ".clob_types",
    "FlexibleDatetime": ".common",
    "GammaMarket": ".gamma_types",
    "GQLPosition": ".data_types",
    "HexString": ".common",
    "Holder": ".data_types",
    "HolderResponse": ".data_types",
    "Keccak256": ".common",
    "Keccak256OrPadded": ".common",
    "LastTradePrice": ".websockets_types",
    "LastTradePriceEvent": ".websockets_types",
    "LeaderboardUser": ".data_types",
    "LiveDataClobMarket": ".websockets_types",
    "LiveDataEvents": ".websockets_types",
    "LiveDataLastTradePriceEvent": ".websockets_types",
    "LiveDataOrderBookSummaryEvent": ".websockets_types",
    "LiveDataOrderEvent": ".websockets_types",
    "LiveDataPriceChangeEvent": ".websockets_types",
    "LiveDataTickSizeChangeEvent": ".websockets_types",
    "LiveDataTradeEvent": ".websockets_types",
    "MakerOrder": ".clob_types",
    "MarketEvent": ".websockets_types",
    "MarketEvents": ".websockets_types",
    "MarketOrderArgs": ".clob_types",
    "MarketResolvedEvent": ".websockets_types",
    "MarketRewards": ".clob_types",
    "MarketStatusChangeEvent": ".websockets_types",
    "MarketValue": ".data_types",
    "Midpoint": ".clob_types",
    "NewMarketEvent": ".websockets_types",
    "OpenOrder": ".clob_types",
    "OpenOrderParams": ".clob_types",
    "OrderArgs": ".clob_types",
    "OrderBookSummary": ".clob_types",
    "OrderBookSummaryEvent": ".websockets_types",
    "OrderCancelResponse": ".clob_types",
    "OrderEvent": ".websockets_types",
    "OrderPostResponse": ".clob_types",
    "OrderSummary": ".clob_types",
    "OrderType": ".clob_types",
    "OptimizedImage": ".gamma_types",
    "PaginatedResponse": ".clob_types",
    "Pagination": ".gamma_types",
    "PastResultsData": ".clob_types",
    "PastResultsResponse": ".clob_types",
    "PartialCreateOrderOptions": ".clob_types",
    "PolygonTrade": ".clob_types",
    "Position": ".data_types",
    "PostOrdersArgs": ".clob_types",
    "Price": ".clob_types",
    "PriceChange": ".websockets_types",
    "PriceChangeEvent": ".websockets_types",
    "PriceChanges": ".websockets_types",
    "PriceHistory": ".clob_types",
    "PriceLevel": ".clob_types",
    "Profile": ".gamma_types",
    "ProfilePosition": ".gamma_types",
    "Quote": ".websockets_types",
    "QuoteEvent": ".websockets_types",
    "Reaction": ".gamma_types",
    "ReactionEvent": ".websockets_types",
    "RelatedEvent": ".websockets_types",
    "Request": ".websockets_types",
    "RequestArgs": ".clob_types",
    "RequestEvent": ".websockets_types",
    "RewardConfig": ".clob_types",
    "RewardMarket": ".clob_types",
    "RewardRate": ".clob_types",
    "Rewards": ".clob_types",
    "RoundConfig": ".clob_types",
    "ScoreStateFields": ".websockets_types",
    "SearchResult": ".gamma_types",
    "Series": ".gamma_types",
    "SignatureType": ".clob_types",
    "SignedOrder": "..utilities.order_builder.model",
    "Sport": ".gamma_types",
    "SportsGameUpdate": ".websockets_types",
    "SportsEventState": ".websockets_types",
    "Spread": ".clob_types",
    "Tag": ".gamma_types",
    "TagRelation": ".gamma_types",
    "Team": ".gamma_types",
    "Template": ".gamma_types",
    "TickSize": ".clob_types",
    "TickSizeChange": ".websockets_types",
    "TickSizeChangeEvent": ".websockets_types",
    "TimeseriesPoint": ".common",
    "Token": ".clob_types",
    "TokenBidAsk": ".clob_types",
    "TokenBidAskDict": ".clob_types",
    "TokenValue": ".clob_types",
    "TokenValueDict": ".clob_types",
    "Trade": ".data_types",
    "TradeParams": ".clob_types",
    "TradeEvent": ".websockets_types",
    "TransactionLog": ".web3_types",
    "TransactionReceipt": ".web3_types",
    "User": ".data_types",
    "UserEvents": ".websockets_types",
    "UserID": ".data_types",
    "UserMetric": ".data_types",
    "UserProfile": ".data_types",
    "UserRank": ".data_types",
    "ValueResponse": ".data_types",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MAP.get(name)
    if module_name is None:
        msg = f"module {__name__!r} has no attribute {name!r}"
        raise AttributeError(msg)

    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
