# Static typing facade for ``pm_apis.types``.
#
# The compatibility package forwards runtime access to ``polymarket_apis.types``.
# These grouped re-exports keep the aggregate models discoverable from
# ``pm_apis.types`` without adding per-module stubs.
from polymarket_apis.types import (
    # Data API models.
    Activity as Activity,
    ActivityType as ActivityType,
    Holder as Holder,
    HolderResponse as HolderResponse,
    Position as Position,
    Trade as Trade,
    User as User,
    UserMetric as UserMetric,
    UserRank as UserRank,
    ValueResponse as ValueResponse,
    # Websocket event models.
    ActivityOrderMatchEvent as ActivityOrderMatchEvent,
    ActivityTradeEvent as ActivityTradeEvent,
    AggOrderBookSummary as AggOrderBookSummary,
    AssetPriceSubscribeEvent as AssetPriceSubscribeEvent,
    AssetPriceUpdateEvent as AssetPriceUpdateEvent,
    BestBidAskEvent as BestBidAskEvent,
    CommentEvent as CommentEvent,
    CryptoPriceSubscribeEvent as CryptoPriceSubscribeEvent,
    CryptoPriceUpdateEvent as CryptoPriceUpdateEvent,
    ErrorEvent as ErrorEvent,
    LastTradePriceEvent as LastTradePriceEvent,
    LiveDataEvents as LiveDataEvents,
    LiveDataLastTradePriceEvent as LiveDataLastTradePriceEvent,
    LiveDataOrderBookSummaryEvent as LiveDataOrderBookSummaryEvent,
    LiveDataOrderEvent as LiveDataOrderEvent,
    LiveDataPriceChangeEvent as LiveDataPriceChangeEvent,
    LiveDataTickSizeChangeEvent as LiveDataTickSizeChangeEvent,
    LiveDataTradeEvent as LiveDataTradeEvent,
    MarketEvents as MarketEvents,
    MarketResolvedEvent as MarketResolvedEvent,
    MarketStatusChangeEvent as MarketStatusChangeEvent,
    NewMarketEvent as NewMarketEvent,
    OrderBookSummaryEvent as OrderBookSummaryEvent,
    OrderEvent as OrderEvent,
    PriceChangeEvent as PriceChangeEvent,
    QuoteEvent as QuoteEvent,
    ReactionEvent as ReactionEvent,
    RequestEvent as RequestEvent,
    SportsGameUpdate as SportsGameUpdate,
    TickSizeChangeEvent as TickSizeChangeEvent,
    TradeEvent as TradeEvent,
    UserEvents as UserEvents,
    # CLOB models and trading-related value types.
    ApiCreds as ApiCreds,
    AssetType as AssetType,
    BidAsk as BidAsk,
    BookParams as BookParams,
    ClobMarket as ClobMarket,
    ClobMarketInfo as ClobMarketInfo,
    ContractConfig as ContractConfig,
    CreateOrderOptions as CreateOrderOptions,
    DailyEarnedReward as DailyEarnedReward,
    MarketIDs as MarketIDs,
    MarketOrderArgs as MarketOrderArgs,
    MarketRewards as MarketRewards,
    Midpoint as Midpoint,
    OpenOrder as OpenOrder,
    OrderArgs as OrderArgs,
    OrderBookSummary as OrderBookSummary,
    OrderCancelResponse as OrderCancelResponse,
    OrderPostResponse as OrderPostResponse,
    OrderType as OrderType,
    PaginatedResponse as PaginatedResponse,
    PartialCreateOrderOptions as PartialCreateOrderOptions,
    PolygonTrade as PolygonTrade,
    PostOrdersArgs as PostOrdersArgs,
    Price as Price,
    PriceHistory as PriceHistory,
    RewardMarket as RewardMarket,
    SignatureType as SignatureType,
    Spread as Spread,
    TickSize as TickSize,
    Token as Token,
    TokenBidAsk as TokenBidAsk,
    TokenBidAskDict as TokenBidAskDict,
    TokenValue as TokenValue,
    TokenValueDict as TokenValueDict,
    # Gamma API models.
    ClobReward as ClobReward,
    Event as Event,
    FeeSchedule as FeeSchedule,
    GammaMarket as GammaMarket,
    Pagination as Pagination,
    Series as Series,
    Tag as Tag,
    # Shared validators and Web3/order-builder models.
    DepositWalletCall as DepositWalletCall,
    EmptyString as EmptyString,
    EthAddress as EthAddress,
    FlexibleDatetime as FlexibleDatetime,
    Keccak256 as Keccak256,
    SignedOrder as SignedOrder,
    TimeseriesPoint as TimeseriesPoint,
)

# Keep ``__all__`` typed without duplicating the runtime export list.
__all__: list[str]
