"""Compatibility re-exports for :mod:`polymarket_apis.types.websockets_types`."""

from __future__ import annotations

from polymarket_apis.types.websockets_types import (
    PriceChange as PriceChange,
    PriceChanges as PriceChanges,
    TickSizeChange as TickSizeChange,
    LastTradePrice as LastTradePrice,
    OrderBookSummaryEvent as OrderBookSummaryEvent,
    PriceChangeEvent as PriceChangeEvent,
    TickSizeChangeEvent as TickSizeChangeEvent,
    LastTradePriceEvent as LastTradePriceEvent,
    BestBidAskEvent as BestBidAskEvent,
    RelatedEvent as RelatedEvent,
    MarketEvent as MarketEvent,
    NewMarketEvent as NewMarketEvent,
    MarketResolvedEvent as MarketResolvedEvent,
    OrderEvent as OrderEvent,
    TradeEvent as TradeEvent,
    ActivityTrade as ActivityTrade,
    Request as Request,
    Quote as Quote,
    AssetPriceSubscribe as AssetPriceSubscribe,
    AssetPriceUpdate as AssetPriceUpdate,
    CryptoPriceSubscribe as CryptoPriceSubscribe,
    CryptoPriceUpdate as CryptoPriceUpdate,
    AggOrderBookSummary as AggOrderBookSummary,
    LiveDataClobMarket as LiveDataClobMarket,
    ActivityTradeEvent as ActivityTradeEvent,
    ActivityOrderMatchEvent as ActivityOrderMatchEvent,
    CommentEvent as CommentEvent,
    ReactionEvent as ReactionEvent,
    RequestEvent as RequestEvent,
    QuoteEvent as QuoteEvent,
    AssetPriceUpdateEvent as AssetPriceUpdateEvent,
    AssetPriceSubscribeEvent as AssetPriceSubscribeEvent,
    CryptoPriceUpdateEvent as CryptoPriceUpdateEvent,
    CryptoPriceSubscribeEvent as CryptoPriceSubscribeEvent,
    LiveDataOrderBookSummaryEvent as LiveDataOrderBookSummaryEvent,
    LiveDataPriceChangeEvent as LiveDataPriceChangeEvent,
    LiveDataLastTradePriceEvent as LiveDataLastTradePriceEvent,
    LiveDataTickSizeChangeEvent as LiveDataTickSizeChangeEvent,
    MarketStatusChangeEvent as MarketStatusChangeEvent,
    LiveDataOrderEvent as LiveDataOrderEvent,
    LiveDataTradeEvent as LiveDataTradeEvent,
    ScoreStateFields as ScoreStateFields,
    SportsEventState as SportsEventState,
    SportsGameUpdate as SportsGameUpdate,
    ErrorEvent as ErrorEvent,
)

__all__ = [
    "PriceChange",
    "PriceChanges",
    "TickSizeChange",
    "LastTradePrice",
    "OrderBookSummaryEvent",
    "PriceChangeEvent",
    "TickSizeChangeEvent",
    "LastTradePriceEvent",
    "BestBidAskEvent",
    "RelatedEvent",
    "MarketEvent",
    "NewMarketEvent",
    "MarketResolvedEvent",
    "OrderEvent",
    "TradeEvent",
    "ActivityTrade",
    "Request",
    "Quote",
    "AssetPriceSubscribe",
    "AssetPriceUpdate",
    "CryptoPriceSubscribe",
    "CryptoPriceUpdate",
    "AggOrderBookSummary",
    "LiveDataClobMarket",
    "ActivityTradeEvent",
    "ActivityOrderMatchEvent",
    "CommentEvent",
    "ReactionEvent",
    "RequestEvent",
    "QuoteEvent",
    "AssetPriceUpdateEvent",
    "AssetPriceSubscribeEvent",
    "CryptoPriceUpdateEvent",
    "CryptoPriceSubscribeEvent",
    "LiveDataOrderBookSummaryEvent",
    "LiveDataPriceChangeEvent",
    "LiveDataLastTradePriceEvent",
    "LiveDataTickSizeChangeEvent",
    "MarketStatusChangeEvent",
    "LiveDataOrderEvent",
    "LiveDataTradeEvent",
    "ScoreStateFields",
    "SportsEventState",
    "SportsGameUpdate",
    "ErrorEvent",
]
