"""Compatibility re-exports for :mod:`polymarket_apis.utilities.order_builder.model`."""

from __future__ import annotations

from polymarket_apis.utilities.order_builder.model import (
    CTF_EXCHANGE_V2_DOMAIN_NAME as CTF_EXCHANGE_V2_DOMAIN_NAME,
    CTF_EXCHANGE_V2_DOMAIN_VERSION as CTF_EXCHANGE_V2_DOMAIN_VERSION,
    CTF_EXCHANGE_V2_ORDER_STRUCT as CTF_EXCHANGE_V2_ORDER_STRUCT,
    EIP712_DOMAIN as EIP712_DOMAIN,
    EOA as EOA,
    POLY_PROXY as POLY_PROXY,
    POLY_GNOSIS_SAFE as POLY_GNOSIS_SAFE,
    POLY_1271 as POLY_1271,
    ORDER_TYPE_STRING as ORDER_TYPE_STRING,
    SOLADY_TYPE_STRING as SOLADY_TYPE_STRING,
    DOMAIN_TYPE_STRING as DOMAIN_TYPE_STRING,
    ORDER_TYPE_HASH as ORDER_TYPE_HASH,
    DOMAIN_TYPE_HASH as DOMAIN_TYPE_HASH,
    SOLADY_TYPE_HASH as SOLADY_TYPE_HASH,
    DEPOSIT_WALLET_NAME_HASH as DEPOSIT_WALLET_NAME_HASH,
    DEPOSIT_WALLET_VERSION_HASH as DEPOSIT_WALLET_VERSION_HASH,
    CTF_EXCHANGE_NAME_HASH as CTF_EXCHANGE_NAME_HASH,
    CTF_EXCHANGE_VERSION_HASH as CTF_EXCHANGE_VERSION_HASH,
    DEPOSIT_WALLET_DOMAIN_SALT as DEPOSIT_WALLET_DOMAIN_SALT,
    BUY_SIDE as BUY_SIDE,
    SELL_SIDE as SELL_SIDE,
    generate_seed as generate_seed,
    prepend_zx as prepend_zx,
    Order as Order,
    OrderData as OrderData,
    OrderTypedDataMessage as OrderTypedDataMessage,
    OrderTypedData as OrderTypedData,
    SignedOrder as SignedOrder,
    OrderBuilder as OrderBuilder,
)

__all__ = [
    "CTF_EXCHANGE_V2_DOMAIN_NAME",
    "CTF_EXCHANGE_V2_DOMAIN_VERSION",
    "CTF_EXCHANGE_V2_ORDER_STRUCT",
    "EIP712_DOMAIN",
    "EOA",
    "POLY_PROXY",
    "POLY_GNOSIS_SAFE",
    "POLY_1271",
    "ORDER_TYPE_STRING",
    "SOLADY_TYPE_STRING",
    "DOMAIN_TYPE_STRING",
    "ORDER_TYPE_HASH",
    "DOMAIN_TYPE_HASH",
    "SOLADY_TYPE_HASH",
    "DEPOSIT_WALLET_NAME_HASH",
    "DEPOSIT_WALLET_VERSION_HASH",
    "CTF_EXCHANGE_NAME_HASH",
    "CTF_EXCHANGE_VERSION_HASH",
    "DEPOSIT_WALLET_DOMAIN_SALT",
    "BUY_SIDE",
    "SELL_SIDE",
    "generate_seed",
    "prepend_zx",
    "Order",
    "OrderData",
    "OrderTypedDataMessage",
    "OrderTypedData",
    "SignedOrder",
    "OrderBuilder",
]
